### ISSUE TITLE
Error signing in: Csrf detected

### ISSUE THREAD

**Issue by mfenner** [datacite/volpino#61]
Error message when coming from ORCID and user is already signed in.

**Comment by richardhallett** [comment]
Moving issue details from datacite/datacite#331 to here for further specific analysis.
User notes:

"When I start the DC Search & Link wizard from the ORCID interface, I'm redirected to https://profiles.datacite.org/ and on top of the page it says Error signing in: Csrf detected. Before I used to get a page with my works (author search matching the first and last name on the ORCID record).

I think this could be because of the redirect URL not matching the one in your production API credentials. The registered redirect URL is https://profiles.datacite.org/users/auth/orcid/callback."

**Comment by mfenner** [comment]
The redirect URL registered with ORCID is correct, and Profiles is then raising an error and redirects to https://profiles.datacite.org.

**Comment by mfenner** [comment]
Background info: https://github.com/datacite/omniauth-orcid/pull/12
