### ISSUE TITLE
People related works - find by authors

### ISSUE THREAD

**Issue by richardhallett** [datacite/volpino#85]
When returning works associated with a user, do additional lookups based upon the name, this will help find related works that are potentially do not have an ORCID record.

**Comment by mfenner** [comment]
Please specify the work here. Until now we have told people to do a search by their name (or any other search string) in DataCite Search when logged in, and then click the "Add to ORCID" button. Should this be better documented, or is there specific functionality we want to develop. Returning works associated with a user based on a query rather than ORCID ID breaks the current functionality, as it will for example return many false positives (depending on the name).

**Comment by richardhallett** [comment]
This is an enhancement, the desire was to be able to do additional lookups based on name.
If the answer then is that we'd prefer to handle this by letting users use the regular search to find their works then we can close.
